### ISSUE TITLE
Number followed by "rd", "nd", "th", "st" don't format correctly with titleCase

### ISSUE THREAD

**Issue by ItIsSeven** [woflowinc/true-case#8]
If you have the word `20TH`, it becomes `20Th` instead of `20th` with `titleCase`
Same for all other examples with `rd`, `nd`, `th`, `st`

**Comment by ItIsSeven** [comment]
I see commits being made, thank you!
I use this tool everyday, so it's nice to see you taking the feedback on!

**Comment by nemrow** [comment]
Fixed with 1de397c7d5b100e4575ed2f44fcb97e6861d143d
